### ISSUE TITLE
How to save the HDR frames in HDR videos?

### ISSUE THREAD

**Issue by seasonmac** [sooyekim/Deep-SR-ITM#1]

**Comment by sooyekim** [comment]
Hello,

Thank you for your interest in our work.
If you run the file test_yuv.m, a video file in YUV format would be generated.

If you wish to convert the .yuv file into .mp4 or other compressed video formats for viewing on HDR devices, the .yuv file should be encoded with any codec supporting HDR videos.

In my case, I downloaded **x265** (H.265/HEVC codec) and **mp4box**,  
and encoded the video with the following lines on matlab:
```
system(['x265.exe --input ', your_yuv_filepath/your_filename, ' --fps 30 --input-res ', '3840x2160', ' -o ', your_filename, '.bin --input-depth 10 --output-depth 10 -q 0 --range limited --transfer 16 --colorprim 9 --colormatrix 9 --psnr']);
system(['mp4box.exe -add ', your_filename,'.bin:FMT=HEVC -fps 30 -new ', _your_filename_,'.mp4']);
```
The flags specify the input/output filenames, frame rate (--fps), input resolution (--input-res), quantization parameter (-q, lower the better quality), etc.  
They should be modified according to your corresponding file.  
The bit-depth, transfer function and color primaries should not be changed.  

For more details on the command line options, please refer to [this url](https://x265.readthedocs.io/en/default/cli.html).
 
Tell me if you have any problems.

Thanks,
Soo Ye

**Comment by seasonmac** [comment]
Thank you for your reply, and learned a lot from your great paper!
As mentioned in your paper, use HDR video files from youtube to extract the frames from them and save them as 10bit images as training data sets.
My question is, how do I extract these 10bit image frames from HDR video?

for example,in your test_yuv.m:
```c++
HDR_file = './data/test/testset_HDR.yuv'; % GT .yuv file
```
How to generate this testset_HDR.yuv file from youtube hdr videos?

**Comment by sooyekim** [comment]
Thank you for the encouraging feedback!

Right, in this case it's more simple.

I downloaded ffmpeg, and used the following command for the conversion:
`ffmpeg -i in.mp4 out.yuv`

As mp4 files include a header with information on the video,  
the above command is sufficient in converting to raw YUV files.

Best,
Soo Ye

**Comment by seasonmac** [comment]
@sooyekim I got it. Thanks a lot.
