### ISSUE TITLE
Video format conversion

### ISSUE THREAD

**Issue by sunzuoxiao** [sooyekim/Deep-SR-ITM#10]
Hi, @sooyekim 
I have some question about the video format,    I got hdr video of yuv format by your code，but，how to convert  HDR.yuv format  to mp4 or mkv。

Thanks！

**Comment by sooyekim** [comment]
Hi @sunzuoxiao ,

Thank you for the interest in our work!
To convert the YUV video file to MP4, please refer to my comment in this closed issue https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377

Best,
Soo Ye

**Comment by sunzuoxiao** [comment]
Hi @sooyekim ，
thank you for the answer. but i get wrong Bit depth, it is still 8 bit.
I build the x265 code and MP4Box,  used yuv format video in /data/test/testset_HDR.yuv. the command in matlab is :
`system(['/home/szx/Desktop/video_yuv/x265_3.2.1/build/linux/x265 --input ', '/home/szx/Desktop/video_yuv/testset_HDR.yuv', ' --fps 30 --input-res ', '3840x2160', ' -o ', '/home/szx/Desktop/video_yuv/testset_HDR', '.bin --input-depth 10 --output-depth 10 -q 0 --range limited --transfer 16 --colorprim 9 --colormatrix 9 --psnr']);
system(['/home/szx/Desktop/video_yuv/gpac-master/bin/gcc/MP4Box -add ', '/home/szx/Desktop/video_yuv/testset_HDR','.bin:FMT=HEVC -fps 30 -new ', '/home/szx/Desktop/video_yuv/testset_HDR','.mp4']);`
![20200110200941](https://user-images.githubusercontent.com/31954170/72152218-4cf6ee00-33e5-11ea-912b-d6078a7aad69.png)
 I have no idear now. Do you know what caused it？
Thanks
