### ISSUE TITLE
extracting testset

### ISSUE THREAD

**Issue by ZeldaM1** [sooyekim/Deep-SR-ITM#11]
@sooyekim 
Hi! Thanks for your sharing. 
I'm trying to extract the pictures from the test file "/data/testset_SDR.mat" and convert them into .png format  but it turns out that the color of the result is not correct. Also, I tried to exchange the channels to avoid the BGR and RGB mistake but it didn't work.  
The following picture is one of my results.  
Can you share the structure of  datasets and give me some suggestions ?
Thanks! 
![123](https://user-images.githubusercontent.com/37172715/72615219-2699fb00-396f-11ea-9664-369aae484f4c.png)

**Comment by sooyekim** [comment]
Hi @ZeldaM1 ,

Thanks for the interest in our work!

Consistent with our paper, the SDR files are actually in the YUV format.
So, to visualize them with PNG files, you should first convert the data from YUV to RGB.

Thanks,
Soo Ye
