### ISSUE TITLE
Qualitative Results

### ISSUE THREAD

**Issue by CVDOU** [sooyekim/Deep-SR-ITM#12]
Hi,
Thanks for the awesome work. The output of the network (as well as GT) seems to have low contrast, possibly caused by that HDR image can't well visualize in my device. Can you share how to visualize the HDR image as showed in your paper.  Thanks.

**Comment by sooyekim** [comment]
Hi @CVDOU ,

Thanks for the interest in our work!

To visualize the HDR results, you should first encode the YUV file into a compressed format such as MP4. Please refer to my comment in this closed issue [#1](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).

If your device supports HDR, you'll be able to directly view the MP4 file on your TV etc.
If it doesn't support HDR, you could try viewing the result using the MPC-HC player with the MadVR renderer (with your PC), which I find to be most similar to viewing on HDR devices.

Please let me know if you have any other questions!

Thanks,
Soo Ye

**Comment by CVDOU** [comment]
> Hi @CVDOU ,
> 
> Thanks for the interest in our work!
> 
> To visualize the HDR results, you should first encode the YUV file into a compressed format such as MP4. Please refer to my comment in this closed issue [#1](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).
> 
> If your device supports HDR, you'll be able to directly view the MP4 file on your TV etc.
> If it doesn't support HDR, you could try viewing the result using the MPC-HC player with the MadVR renderer (with your PC), which I find to be most similar to viewing on HDR devices.
> 
> Please let me know if you have any other questions!
> 
> Thanks,
> Soo Ye

Thanks a lot. I understand how to show HDR images in a HDR device.  But how to show them in your paper?
Whether  the results showed in your paper are directly 16 bit HDR images (GTs and outputs) or tone-mapping SDR images? If HDR images, how to show them without losing contrast.

**Comment by sooyekim** [comment]
For visualizations in the paper, I used the second way with the MPC-HC player + madVR renderer, since it's not possible to show 10 bits/pixel on paper. I found their tone-mapped results to be most similar to actually viewing them in real HDR. You can use the screenshot feature in the player to save the video frames. 

Hope this helps!

**Comment by CVDOU** [comment]
> For visualizations in the paper, I used the second way with the MPC-HC player + madVR renderer, since it's not possible to show 10 bits/pixel on paper. I found their tone-mapped results to be most similar to actually viewing them in real HDR. You can use the screenshot feature in the player to save the video frames.
> 
> Hope this helps!

Thank you for your patient reply. My issue is well addressed.
