### ISSUE TITLE
something werid about the testset_HDR...

### ISSUE THREAD

**Issue by zhangqizky** [sooyekim/Deep-SR-ITM#17]
Hi, sooyekim.Thanks for releasing this awesome repo, 
I wonder if I get the images from mat file correctly, because the HDR file is a little werid compared to the SDR, as follows..
![image](https://user-images.githubusercontent.com/23207132/90393084-a5e8dc00-e0c2-11ea-98b1-863fc9171da0.png)

And the convert code...
![image](https://user-images.githubusercontent.com/23207132/90393196-d466b700-e0c2-11ea-9e18-4b0d4cffe3d8.png)

Do I covert the mat file correctly for the HDR mat? It looks really werid...even not as good as the SDR file.
Could you give me some advice?
Thanks in advance😊

**Comment by sooyekim** [comment]
Hi @zhangqizky ,

Thanks for the interest in our work! This is a good question.
Since the RGB primaries are different (BT.709 vs BT.2020), the conversion formula is different for SDR and HDR data, and simply using cv2.cvtColor wouldn't convert YUV -> RGB correctly for BT.2020 primaries.

To correctly convert from YUV to RGB with BT.2020 primaries, please refer to the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG. You could refer to sections 4.9 and 4.10.2 for the correct conversion formula. In MATLAB code, this would look something like:
```
function [RGB] = YUV2RGB_BT2020(YUV)

Bitdepth=10;
D_Y = YUV(:,:,1);
D_u = YUV(:,:,2);
D_v = YUV(:,:,3);

%Inverse quant 10b
Y=ClampImg((D_Y/bitshift(1, Bitdepth-8) - 16)/219, 0, 1);
D_Cb=ClampImg((D_u/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
D_Cr=ClampImg((D_v/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);

%Y'CbCr to R'G'B'
% BT 2020
A = [1 0.00000000000000 1.47460000000000;
     1 -0.16455312684366 -0.57135312684366;
     1 1.88140000000000 0.00000000000000];

RGB(:,:,1) = ClampImg(Y(:,:,1) + A(1,3)*D_Cr, 0, 1);
RGB(:,:,2) = ClampImg(Y(:,:,1) + A(2,2)*D_Cb + A(2,3)*D_Cr, 0, 1);
RGB(:,:,3) = ClampImg(Y(:,:,1) + A(3,2)*D_Cb, 0, 1);

end
```

However, note that the HDR frame wouldn't look as good as the SDR frame even when converted in this way, **if you are using an SDR display to view the frames**. The HDR videos would look best on an HDR display, in which case it could be easier to visualize the .yuv files after converting to .mp4 as mentioned in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).

If you don't have an HDR display available, I recommend you to use the MPC-HC player with MadVR as mentioned in README.txt of the provided supplementary material.

Let me know if you need anything else!
Thanks,
Soo Ye

**Comment by tuvovan** [comment]
> Hi @zhangqizky ,
> 
> Thanks for the interest in our work! This is a good question.
> Since the RGB primaries are different (BT.709 vs BT.2020), the conversion formula is different for SDR and HDR data, and simply using cv2.cvtColor wouldn't convert YUV -> RGB correctly for BT.2020 primaries.
> 
> To correctly convert from YUV to RGB with BT.2020 primaries, please refer to the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG. You could refer to sections 4.9 and 4.10.2 for the correct conversion formula. In MATLAB code, this would look something like:
> 
> ```
> function [RGB] = YUV2RGB_BT2020(YUV)
> 
> Bitdepth=10;
> D_Y = YUV(:,:,1);
> D_u = YUV(:,:,2);
> D_v = YUV(:,:,3);
> 
> %Inverse quant 10b
> Y=ClampImg((D_Y/bitshift(1, Bitdepth-8) - 16)/219, 0, 1);
> D_Cb=ClampImg((D_u/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> D_Cr=ClampImg((D_v/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> 
> %Y'CbCr to R'G'B'
> % BT 2020
> A = [1 0.00000000000000 1.47460000000000;
>      1 -0.16455312684366 -0.57135312684366;
>      1 1.88140000000000 0.00000000000000];
> 
> RGB(:,:,1) = ClampImg(Y(:,:,1) + A(1,3)*D_Cr, 0, 1);
> RGB(:,:,2) = ClampImg(Y(:,:,1) + A(2,2)*D_Cb + A(2,3)*D_Cr, 0, 1);
> RGB(:,:,3) = ClampImg(Y(:,:,1) + A(3,2)*D_Cb, 0, 1);
> 
> end
> ```
> 
> However, note that the HDR frame wouldn't look as good as the SDR frame even when converted in this way, **if you are using an SDR display to view the frames**. The HDR videos would look best on an HDR display, in which case it could be easier to visualize the .yuv files after converting to .mp4 as mentioned in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).
> 
> If you don't have an HDR display available, I recommend you to use the MPC-HC player with MadVR as mentioned in README.txt of the provided supplementary material.
> 
> Let me know if you need anything else!
> Thanks,
> Soo Ye

the input yuv for the function is in 8bits or 10 bits? or just 0-1?

**Comment by sooyekim** [comment]
@tuvovan The input would be 10 bits! (0-1023)

**Comment by zhangqizky** [comment]
> @tuvovan The input would be 10 bits! (0-1023)

Thanks a lot for reply!!!
I train a model use the train videos you recommended, the GT is use ffmpeg turn the hdr video into yuv and then turn to numpy. 
When I test the model use a sdr video, I got the output which is between 0-1023, How do I correctly show it in a real hdr monitor? I mean , how do I convert the model predict output(which is between 0-1023) frames into a video ,which can correctly show in a real hdr monitor? I am sorry My english is like trash...If you get what I mean, Could you give me some advices, thanks very much!!!

**Comment by sooyekim** [comment]
@zhangqizky 
When you have the .yuv file with pixel values between 0-1023, you should convert the raw video to .mp4 to view on a HDR display.
Please refer to [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377), also mentioned in the last part of my previous comment.
Thanks!

> Hi @zhangqizky ,
> 
> Thanks for the interest in our work! This is a good question.
> Since the RGB primaries are different (BT.709 vs BT.2020), the conversion formula is different for SDR and HDR data, and simply using cv2.cvtColor wouldn't convert YUV -> RGB correctly for BT.2020 primaries.
> 
> To correctly convert from YUV to RGB with BT.2020 primaries, please refer to the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG. You could refer to sections 4.9 and 4.10.2 for the correct conversion formula. In MATLAB code, this would look something like:
> 
> ```
> function [RGB] = YUV2RGB_BT2020(YUV)
> 
> Bitdepth=10;
> D_Y = YUV(:,:,1);
> D_u = YUV(:,:,2);
> D_v = YUV(:,:,3);
> 
> %Inverse quant 10b
> Y=ClampImg((D_Y/bitshift(1, Bitdepth-8) - 16)/219, 0, 1);
> D_Cb=ClampImg((D_u/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> D_Cr=ClampImg((D_v/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> 
> %Y'CbCr to R'G'B'
> % BT 2020
> A = [1 0.00000000000000 1.47460000000000;
>      1 -0.16455312684366 -0.57135312684366;
>      1 1.88140000000000 0.00000000000000];
> 
> RGB(:,:,1) = ClampImg(Y(:,:,1) + A(1,3)*D_Cr, 0, 1);
> RGB(:,:,2) = ClampImg(Y(:,:,1) + A(2,2)*D_Cb + A(2,3)*D_Cr, 0, 1);
> RGB(:,:,3) = ClampImg(Y(:,:,1) + A(3,2)*D_Cb, 0, 1);
> 
> end
> ```
> 
> However, note that the HDR frame wouldn't look as good as the SDR frame even when converted in this way, **if you are using an SDR display to view the frames**. The HDR videos would look best on an HDR display, in which case it could be easier to visualize the .yuv files after converting to .mp4 as mentioned in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).
> 
> If you don't have an HDR display available, I recommend you to use the MPC-HC player with MadVR as mentioned in README.txt of the provided supplementary material.
> 
> Let me know if you need anything else!
> Thanks,
> Soo Ye

**Comment by zhangqizky** [comment]
> @zhangqizky
> When you have the .yuv file with pixel values between 0-1023, you should convert the raw video to .mp4 to view on a HDR display.
> Please refer to [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377), also mentioned in the last part of my previous comment.
> Thanks!
> 
> > Hi @zhangqizky ,
> > Thanks for the interest in our work! This is a good question.
> > Since the RGB primaries are different (BT.709 vs BT.2020), the conversion formula is different for SDR and HDR data, and simply using cv2.cvtColor wouldn't convert YUV -> RGB correctly for BT.2020 primaries.
> > To correctly convert from YUV to RGB with BT.2020 primaries, please refer to the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG. You could refer to sections 4.9 and 4.10.2 for the correct conversion formula. In MATLAB code, this would look something like:
> > ```
> > function [RGB] = YUV2RGB_BT2020(YUV)
> > 
> > Bitdepth=10;
> > D_Y = YUV(:,:,1);
> > D_u = YUV(:,:,2);
> > D_v = YUV(:,:,3);
> > 
> > %Inverse quant 10b
> > Y=ClampImg((D_Y/bitshift(1, Bitdepth-8) - 16)/219, 0, 1);
> > D_Cb=ClampImg((D_u/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> > D_Cr=ClampImg((D_v/bitshift(1, Bitdepth-8) - 128)/224, -0.5, 0.5);
> > 
> > %Y'CbCr to R'G'B'
> > % BT 2020
> > A = [1 0.00000000000000 1.47460000000000;
> >      1 -0.16455312684366 -0.57135312684366;
> >      1 1.88140000000000 0.00000000000000];
> > 
> > RGB(:,:,1) = ClampImg(Y(:,:,1) + A(1,3)*D_Cr, 0, 1);
> > RGB(:,:,2) = ClampImg(Y(:,:,1) + A(2,2)*D_Cb + A(2,3)*D_Cr, 0, 1);
> > RGB(:,:,3) = ClampImg(Y(:,:,1) + A(3,2)*D_Cb, 0, 1);
> > 
> > end
> > ```
> > 
> > 
> > However, note that the HDR frame wouldn't look as good as the SDR frame even when converted in this way, **if you are using an SDR display to view the frames**. The HDR videos would look best on an HDR display, in which case it could be easier to visualize the .yuv files after converting to .mp4 as mentioned in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).
> > If you don't have an HDR display available, I recommend you to use the MPC-HC player with MadVR as mentioned in README.txt of the provided supplementary material.
> > Let me know if you need anything else!
> > Thanks,
> > Soo Ye

Hi,Soo Ye
Thanks for replying.
The comparsion figure with other methods in your paper, like this:
![image](https://user-images.githubusercontent.com/23207132/104703643-8aa5f980-5752-11eb-9d52-f0e8fe81fd7e.png)

how did you get the outputs part show normally on a sdr player? also by the way  "YUV2RGB_BT2020" from a one frame yuv to a one frame rgb, or screenshots from a video played on hdr display?
Really thanks if you share about this...thanks soooo much
Zhangqi

**Comment by haifangqin** [comment]
hi, thanks for your good discussion!

Could you explain the function named **ClampImg**?

I can not found it in anywhere:)

**Comment by sooyekim** [comment]
Hi @haifangqin ,
Could you please point to the location of the function? Thanks!

**Comment by haifangqin** [comment]
**ClampImg((D_Y/bitshift(1, Bitdepth-8) - 16)/219, 0, 1);**

the **ClampImg** means clip the numbers to the range [0, 1] ?

**Comment by sooyekim** [comment]
Do you mean [this line](https://github.com/sooyekim/Deep-SR-ITM/blob/0437c92e956f416c82a89d649e83983c74ddc48c/utils/mPSNR_HDR.m#L106) in utils/mPSNR_HDR.m? This function was modified from the version in [HDR_Toolbox](https://github.com/banterle/HDR_Toolbox) (in HDR_Toolbox/source_code/Metrics/mPSNR.m). Please refer to that repo for more details. ClampImg.m is in HDR_Toolbox/source_code/util.

**Comment by haifangqin** [comment]
thanks! got it！

**Comment by sooyekim** [comment]
@zhangqizky Just noticed that I hadn't replied to your previous comment. Some time has passed since then, but in case you're still wondering: 1) The comparison figures were captured using the MPC-HC player with the MadVR renderer as mentioned in Section 4.1 in our paper. 2)  YUV2RGB_BT2020 converts a YUV frame to an RGB frame.
