### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by tuvovan** [sooyekim/Deep-SR-ITM#18]
Hi,

Thank you for your great work.

I'm working on reproducing your paper using python so I wonder whether you can provide the data in the original form (not in mat form) including ldr and hdr (groundtruth)?

Thank you!

**Comment by sooyekim** [comment]
Hi @tuvovan ,
Thanks for the interest in our work, it's great that you are implementing it on python!
Regarding the original data, please refer to [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/8#issuecomment-564816839).

**Comment by tuvovan** [comment]
thanks, I will have a look at it.
