### ISSUE TITLE
A technical question about extracting .hdr images (i.e. frames) from HDR video

### ISSUE THREAD

**Issue by kekezhang112** [sooyekim/Deep-SR-ITM#20]
Hi, sooyekim:

I have read your great works and I want to try my idea in SDR/LDR video iTO. 

I wonder that how to extract '.hdr' images (i.e. each frames) from HDR videos downloaded from '4K Media.org'. The forms of videos are '.mp4', '.mkv' and '.ts'. 

Could you please help me? Thank you very much!

Best regards

Keke Zhang

**Comment by sooyekim** [comment]
Hi @kekezhang112 ,

Thanks for the interest in our work!
Since our method converts 8-bit SDR frames to 10-bit HDR frames (in the pixel domain, and thus, YUV), I used ffmpeg to extract YUV frames from .mp4, .mkv, etc.
You wouldn't really need .hdr images in this case.

Thanks!
Soo Ye

**Comment by kekezhang112** [comment]
@sooyekim Thank you for your reply!
