### ISSUE TITLE
questions about Deep SR_ITM and JSI-GAN

### ISSUE THREAD

**Issue by haifangqin** [sooyekim/Deep-SR-ITM#23]
hi, I notice that JSI_GAN are very strong relation with the Deep SR_ITM.

Since I am now re-implement the JSI-GAN, I happended some problems , could you help me out for this?

https://github.com/JihyongOh/JSI-GAN/issues/19

the testing PSNR is weird

**Comment by sooyekim** [comment]
Let's continue the discussion in the JSI-GAN repo. Closing this thread
