### ISSUE TITLE
Question about the HDR-VDP score

### ISSUE THREAD

**Issue by CS-GangXu** [sooyekim/Deep-SR-ITM#24]
Hi, @sooyekim  thanks for your great work! I want to ask a question about the evaluation pipeline of HDRVDP-2.2.1. I want to know what should I do after obtaining the output YUV data with the .mat format to get the same HDRVDP score claimed in the paper. Could you provide the HDRVDP evaluation code?

Thanks in advance.

**Comment by sooyekim** [comment]
Hi @CS-GangXu ,
Thanks for your interest in our work!
As mentioned in the paper, we measured HDR-VDP-2.2.2 with the luminance option and pixel per degrees = 30.  
Please refer to the below code:
```
pred_YUV = double(pred_YUV)/1023;
gt_YUV = double(gt_YUV)/1023;
    
psnr_val = psnr(pred_YUV, gt_YUV, 1);
ssim_val = ssim(pred_YUV, gt_YUV);
mpsnr_val = mPSNR_HDR(pred_YUV, gt_YUV, -3, 3);
msssim_val = msssim(pred_YUV*1023, gt_YUV*1023, 1023);

% hdr-vdp 
[HDR_Ylin,~,~] = rgb2yuv_hdr(inv_PQTF(gt_YUV*1023));
[pred_Ylin,~,~] = rgb2yuv_hdr(inv_PQTF(pred_YUV*1023));
hdr_vdp_1 = hdrvdp(HDR_Ylin, pred_Ylin, 'luminance', 30);
hdr_vdp_val = hdr_vdp_1.Q;
```
For the functions, see [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/19#issuecomment-711607571).

**Comment by CS-GangXu** [comment]
Thanks for your reply! It's very kind of you to provide this code.
