### ISSUE TITLE
About calculation of SSIM

### ISSUE THREAD

**Issue by clearlon** [sooyekim/Deep-SR-ITM#25]
Hi,
Thanks for the awesome work. 
I can't reproduce the **SSIM** in the **JSI-GAN paper** when using `utils/ssim_index_new.m` to calculate the **SSIM** between GT and Pred. The Pred is obtained by direct inference from `JSI-GAN/checkpoint_dir`. Specifically, the SSIMs I calculated for JSInet and JSI-GAN are **0.9401** and **0.9330**, respectively. The codes are as follows:
```
gt_img = double(imread(gt_folder))
pred_img = double(imread(pred_folder))
[mssim, ssim_map, mcs, cs_map] = ssim_index_new(gt_img, pred_img, K, win, 1023)
```

**Comment by sooyekim** [comment]
I've addressed your comment on the [JSI-GAN repo](https://github.com/JihyongOh/JSI-GAN/issues/28#issuecomment-1085480584). Thanks!
