### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by Schizophreni** [sooyekim/Deep-SR-ITM#3]
Thanks for your awesome work.
How can I change the YUV output from BT.2020 range back to BT.709 range for displaying on my
screen?

**Comment by Schizophreni** [comment]
> Thanks for your awesome work.
> How can I change the YUV output from BT.2020 range back to BT.709 range for displaying on my
> screen?

I've found the solution by trying different mapping function from YUV to RGB, hhh
The uint8 YUV has been modulated by subtracting Y with 16 for SDR image.

**Comment by sooyekim** [comment]
Hi,

Thanks for your interest in our work.
To convert to RGB709, note that you would have to convert from YUV2020 to RGB2020, then to RGB709.
Also, please note that our method is actually not intended for viewing in RGB709.
(It's intended for viewing on HDR displays with BT.2020 standard)

Thank you.
Soo Ye

**Comment by Schizophreni** [comment]
Thanks for your reply. got that, seems a laborious task, I will try it.
I just tried several methods to change the YUV2020 to RGB2020, then to RGB709, but the result is not good, there must be information loss during the path, I will keep trying.
Congratulations to your splendid work!
