### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Auth0rM0rgan** [sooyekim/Deep-SR-ITM#5]
Hey @sooyekim, 

Nice work and thanks for sharing your code! I wonder if you can help me with visualizing intermediate feature maps as you did in your paper (Figure 8). 

Thanks!

**Comment by sooyekim** [comment]
Hi @Auth0rM0rgan!

For visualizing the feature maps, you should first set net.conserveMemory to False in the testing options, to save the intermediate variables.

`net.conserveMemory = False;`

In the provided code, this option is set to True to save memory space. Note that depending on your GPU, there may be a memory error after changing this option. In this case, you should try cropping the input image into a smaller resolution.

With this set up, the intermediate feature maps will be saved in net.vars and you can bring it to the CPU using the 'gather' function like I did for the variable pred. For visualization, you can use imshow() with appropriate normalization for each feature map.

Best,
Soo Ye
