### ISSUE TITLE
No super resolution.

### ISSUE THREAD

**Issue by liulizhou** [sooyekim/Deep-SR-ITM#7]
Hi, @sooyekim 
Did you try just `ITM` but not change video resolution(x1) ? 
I remove pixel_shuffle layer and resize your data to same resolution(python implement), but video letter color of the result is not correct. Can you give me some suggestions ?
Thanks!

**Comment by sooyekim** [comment]
Hi @liulizhou ,

I haven't tried only performing ITM without SR, but I don't see any reason why it wouldn't work if the pixel shuffle layer is removed and the data is resized..

If the color is wrong, maybe it's the normalization? 
(The prediction should be multiplied by 1023 to get the YUV frame)
Or how are you visualizing the color?

Thanks for your continued interest in our work!
Soo Ye

**Comment by liulizhou** [comment]
Hi @sooyekim 
I encode YUV frame with x265, and visualize video on s9 mobile phone. Just video subtitle edge appear anomalous color,  and the rest of video are normal.
Thanks for your help!
Liu Lizhou

**Comment by sooyekim** [comment]
Hi @liulizhou ,

Please have a check whether the bit depth, transfer function and the color primaries are properly set when you encoded with x265. 
You could refer to the command line [here](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).

Best,
Soo Ye

**Comment by liulizhou** [comment]
> Hi @liulizhou ,
> 
> Please have a check whether the bit depth, transfer function and the color primaries are properly set when you encoded with x265.
> You could refer to the command line [here](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).
> 
> Best,
> Soo Ye

Hi @sooyekim 
I output encoded video mediainfo, i think bit depth and TF are correct. In addition video subtitle edge color sometimes was anomalous, and not always appear. I give a anomalous image at the end.
```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@Main
Codec ID                                 : hev1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 41s 709ms
Bit rate                                 : 10.9 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.218
Stream size                              : 54.0 MiB (100%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Color range                              : Limited
Color primaries                          : BT.2020
Matrix coefficients                      : BT.2020 non-constant
```
[A anomalous example](https://github.com/liulizhou/images/blob/master/subtitle.png)

**Comment by sooyekim** [comment]
Hi @liulizhou ,

The video spec seems right..Could you also show me the input?
Also, are you clipping the predicted frames to be in the range [0, 1023] ?
Haven't seen this type of artifact before..

Thanks,
Soo Ye

**Comment by liulizhou** [comment]
@sooyekim 
input spec:
```
Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings, BVOP                    : No
Format settings, Matrix                  : Default
Format settings, GOP                     : N=1
Codec ID                                 : 61
Duration                                 : 1mn 59s
Bit rate mode                            : Constant
Bit rate                                 : 50.0 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) fps
Minimum frame rate                       : 23.810 fps
Maximum frame rate                       : 24.390 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 1.006
Time code of first frame                 : 00:24:58:14
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Closed
Stream size                              : 715 MiB (100%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
```
1. Yes, i clip the predict frames to [0, 1023]
2. I convert `mp4` to `yuv420`, and then upsample U, V channel to the same resolution with Y.
3. I want to know how you make your dataset. Did you upload hdr video to youtube and then download sdr that youtube converted ? If do like that, youtube will recode the video with a low bit rate, which will lead to poor video quality.
4. Can you provide the hdr website of youtube which you use?

Thanks for help!
Liu Lizhou

**Comment by sooyekim** [comment]
Hi @liulizhou ,

Thank you for providing the input spec, but could you provide the input image/patch that produces the 'anomalous example'?

I downloaded the HDR videos from 4kmedia.org , and then found the same videos on Youtube (already uploaded on multiple channels), which were downloaded as SDR versions. I tried to find the channel that has the highest quality and also tried to find the downloader that gave me the highest quality.

Thanks,
Soo Ye

**Comment by liulizhou** [comment]
Hi, @sooyekim 
Sorry for being late.
I upload input and hdr result example.
[sdr input](https://github.com/liulizhou/images/blob/master/sdr15.png)
I circle the anomalous location of the result.
[hdr result](https://github.com/liulizhou/images/blob/master/genhdr112_edit.png)

Thanks for help!
Liu Lizhou

**Comment by sooyekim** [comment]
Hi @liulizhou ,

I'm sorry I don't have a clear explanation for the results..
I guess some slight pixel changes (invisible to the human eye) in the input are irritating the CNN.
Also, there were no subtitles present in the training patches, so maybe this is also the reason.

Thanks,
Soo Ye

**Comment by pinderpeng** [comment]
@liulizhou Have you retrained the model for video resolution x1? Maybe it helps.
